/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IQFirstContract } from "./IQFirstContract";

export { IQFirstContract__factory } from "./factories/IQFirstContract__factory";
