/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { UserInformation } from "./UserInformation";

export { UserInformation__factory } from "./factories/UserInformation__factory";
